# Site settings
title: Happy Valentines Day!
email: your-email@domain.com
url: "https://mlem3131.github.io"
baseurl: "/Happy-Valentines-Day"

description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "your keywords, separated by commas"
skills: "With love, from Maadhav"
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: FF4C8E  # A romantic pink
  primary-rgb: "255,76,142"  
  secondary: A2122F  # Deep red
  secondary-dark: 750021  # Darker red


# Footer settings
footer:
  copyright: "Made with ❤️ for Thapasyaa J"
  location: "come over nigga"
  social: "send me reels"
  credits: "A special website designed with love 💕"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: instagram
    url: http://instagram.com/maadhav_arora
 

# Postal address (add as many lines as necessary)
address:
  - line: CP residence, civil lines Gurgaon
  

# Credits content
credits: Maadhav

# Build settings
markdown: kramdown
permalink: pretty

#for posts
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      permalink: ""
